version: "3"
services:
  app:
    image: transcopy
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
    networks:
      - private
    expose:
      - "8090"
    ports:
      - "8090:80"
    environment:
      CONTAINER_ROLE: "app"

  queue:
    image: transcopy
    depends_on:
      - app
      - redis
    networks:
      - private
    environment:
      CONTAINER_ROLE: "queue"

  redis:
    image: redis:4
    networks:
      - private

networks:
  private:
