#!/usr/bin/env bash

set -e

role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}


until echo 'PING' | nc -w 1 redis 6379 | grep -q PONG
do
    echo "Waiting for Redis connection..."
    sleep 5
done

composer self-update

php /var/www/html/artisan config:cache

if [ "$role" = "app" ]; then

    echo "Starting app"
    touch /tmp/sqlite/torrents.sqlite
    php /var/www/html/artisan migrate
    exec apache2-foreground

elif [ "$role" = "queue" ]; then

    # php /var/www/html/artisan horizon
    echo "Starting queue"
    php /var/www/html/artisan queue:work --timeout=14000 --tries=1

else
    echo "Could not match the container role \"$role\""
    exit 1
fi
